version: "3.9"

services:
  web:
    build: .
    container_name: django
    command: ["/bin/bash", "/app/entrypoint.sh"]
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_PASSWORD: admin
      TZ: Asia/Tokyo
    volumes:
      - ./:/app
    ports:
      - "8000:8000"